### ISSUE TITLE
Need to fix TYPO in HTTP response header

### ISSUE THREAD

**Issue by nanishin** [MrYsLab/s2a_fm#13]
Hi,

During test, I found one TYPO in HTTP response header.
Please refer below my local patch.

In scratch_http_server.py
`$ git diff scratch_http_server.py`
`diff --git a/scratch_http_server.py b/scratch_http_server.py`
`index e8337da..ec763b7 100644`
`--- a/scratch_http_server.py`
`+++ b/scratch_http_server.py`
`@@ -104,7 +104,7 @@ class GetHandler(BaseHTTPRequestHandler):`
`         # http_response = str(response + calf)`
`         http_response = "HTTP/1.1 200 OK" + calf`
`        http_response += "Content-Type: text/html; charset=ISO-8859-1" + calf`
`-        http_response += "Content-Length" + str(len(response)) + calf`
`+        http_response += "Content-Length: " + str(len(response)) + calf`
`         http_response += "Access-Control-Allow-Origin: *" + calf`
`         http_response += calf`
 `        #add the response to the nonsense above`

Regards,

**Comment by MrYsLab** [comment]
You are correct, there should be a colon in "Content-Length", but other than the typographical error, is this causing any issues for you?

**Comment by nanishin** [comment]
@MrYsLab I just wanted to report syntax correction to you. Actually Scratch2 doesn't matter it.

**Comment by MrYsLab** [comment]
@nanishin Thanks. I am going to leave this as is since it is not causing a problem. I seem to remember to that I used an example from the Scratch documentation in constructing the header format. That documentation has long been removed, so I cannot verify that. I

Thanks again for pointing this out.
