### ISSUE TITLE
Issue moved from s2aio

### ISSUE THREAD

**Issue by MrYsLab** [MrYsLab/s2a_fm#15]
This is the original issue from @sobreira reported in s2aio issue #8:

Hi MrYsLab.
I'd really like to thank you for great work, in fact we try to widespread the knownledge about your creation for lots of schools in Brazil.
We still use the Python 2.7 and I try to connect the HC-SR04.
I followed all steps above mentioned however Scratch or Snap can´t read any information from the sensor.

To make a test, I have installed the new Python and I did what you asked on your comment from25 Jul.
By this worked fine well, however, back to PyMata, Python 2.7 and s2a_fm, the Sonar not work.

For all the other other things, the system performs as expected.

I really appreciate your help on this.

Thanks!

Edson
hackeduca.com

**Comment by MrYsLab** [comment]
I just tested on Windows 10 with the following script:

![screenshot from 2016-12-09 10-24-01](https://cloud.githubusercontent.com/assets/5189838/21054017/e2918eb2-bdf9-11e6-9c02-0e4dae441b1f.png)

The program ran correctly.

I first loaded the Scratch extension file s2a_fm.s2e and then ran the script.

Could you please do the same and tell me if things are working for you?

**Comment by sobreira** [comment]
Hi Alan, actually I found out my problem.
I was using an old version of PySerial and also my Python was outdated.
I updated everything and once more worked perfect

Thanks a lot for your support

Edson Sobreira
hackeduca.com
