### ISSUE TITLE
Port not open

### ISSUE THREAD

**Issue by indavidjool** [MrYsLab/s2a_fm#17]
When I attempt to run the install as per the reference manual (`python s2a_fm.py /dev/ttyACM0`) the RX LED on my Arduino Mega blinks rapidly but then I get the following exception: **serial.serialutil.SerialException: Attempting to use a port that is not open**.  
As far as I can tell I did not skip an installation step. Attached is the terminal output for the complete messages.
![s2a_fm error](https://user-images.githubusercontent.com/11023928/28142400-08053d52-67a4-11e7-95b2-6a0862944979.png)

**Comment by indavidjool** [comment]
My apologies.  I did skip an installation step:
**Load Standard Firmata into the Arduino from the examples directory of the Firmata library included
with the Arduino IDE**
Perhaps the reference manual requires a few more words explaining the steps to take to do this.

**Comment by MrYsLab** [comment]
I am glad that you figured it out and it is working for you. I will keep that in mind if I update the documentation.
